config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'articles#index'

  devise_for :users
  resources :users, only: [:show]
  resources :follow

  # resources deal with all CRUD operations
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# Class to define the articles entity
class Article < ApplicationRecord
  include Visible

  # Relations
  belongs_to :user
  has_many :comments, dependent: :destroy

  # Condition verification
  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  # Define comments score method
  def score
    l = comments.length.to_f
    return 0 if l.zero?

    (comments.reduce(0) { |p, a| p + a.score } / l).round(1)
  end
end

app/models/comment.rb
# frozen_string_literal: true

# Class to define the comments entity
class Comment < ApplicationRecord
  include Visible
  belongs_to :article

  validates :score, inclusion: { in: (1..5).to_a }

  # Condition verification
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/concerns/visible.rb
# frozen_string_literal: true

# Module to deal with the visibility of articles and comments
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived]

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :followee, foreign_key: 'followee_id', class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Articles relations
  has_many :article, dependent: :destroy

  # Followers
  has_many :follower_follows, foreign_key: :followee_id, class_name: 'Follow', dependent: :destroy
  has_many :followers, through: :follower_follows, source: :follower, dependent: :destroy

  # Followee
  has_many :followee_follows, foreign_key: :follower_id, class_name: 'Follow', dependent: :destroy
  has_many :followees, through: :followee_follows, source: :followee, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# Class to deal with the articles entity
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  # READ
  def show
    @article = Article.find(params[:id])
  end

  # CREATE
  def new
    if user_signed_in?
      @article = Article.new
    else
      redirect_to root_path
    end
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  # UPDATE
  def edit
    @article = Article.find(params[:id])
    redirect_to @article unless user_signed_in? && current_user[:id] == @article.user_id
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  # DELETE
  def destroy
    @article = Article.find(params[:id])
    if user_signed_in? && current_user[:id] == @article.user_id
      @article.destroy
      redirect_to root_path
    else
      redirect_to @article
    end
  end

  private

  def article_params
    form = params[:article].merge({ user_id: current_user[:id] })
    form.permit(:title, :body, :status, :user_id)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Class to deal with the comments entity
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @blogger = User.find(@article[:user_id]).followers
    @comments = @article.comments.create(comment_params) if user_signed_in? && @blogger.include?(current_user)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status, :score)
  end
end

app/controllers/follow_controller.rb
# frozen_string_literal: true

# Class to deal with the follow relation
class FollowController < ApplicationController
  def create
    @article = Article.find(params[:article])
    @follower = User.find(current_user[:id])
    @followee = User.find(@article[:user_id])
    @follow = Follow.new(follower: @follower, followee: @followee)
    @follow.save
    redirect_to article_path(@article)
  end

  def destroy
    @follow = Follow.where(follower_id: params[:follower], followee_id: params[:followee])
    @follow.destroy(@follow[0][:id]) if @follow && user_signed_in? && current_user[:id] == @follow[0][:follower_id]
    redirect_to current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_comments_score.html.erb
<div class="container d-inline">
    <div class="row">
        <div class="col-6 d-table">
            <img src="/images/comment.svg" style="max-width:40%; min-width:20px">
            <span class="text-white position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary">
                <%= article.comments.length%>
            </span>
        </div>

        <div class="col-6 d-table">
            <img src="/images/like.svg" style="max-width:40%; min-width:20px">
            <span class="text-white position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary">
                <%= article.score %>
            </span>
        </div>
    </div>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div class="container mt-5">
        <div class="d-grid d-sm-flex justify-content-sm-center pr-3 pb-3 input-group">
            <span class="input-group-text"><%= form.label :title %></span><br>
            <%= form.text_field :title, class: "form-control" %>
            <% article.errors.full_messages_for(:title).each do |message|%>
                <div><%= message %></div>
            <% end %>
        </div>

        <div class="d-grid d-sm-flex justify-content-sm-center pr-3 pb-3 input-group-lg">
            <span class="input-group-text"><%= form.label :body %></span><br>
            <%= form.text_area :body, class: "form-control", rows: 10 %>
            <% article.errors.full_messages_for(:body).each do |message|%>
                <div><%= message %></div>
            <% end %>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class='col-6 d-grid justify-content-sm-center m-auto'>
                <p class="text-center d-flex justify-content-sm-center" style="font-size:20px">
                    Comment status
                </p>
                <div class="container d-flex justify-content-center">
                    <div class="btn-group d-table justify-content-sm-center" role="group">
                        <label class="btn btn-outline-primary" for="status1"> Public
                            <%= form.radio_button :status, 'public', id: "status1",class: "btn-check", autocomplete: "off",checked: true%>
                        </label>

                        <label class="btn btn-outline-primary" for="status2"> Private
                            <%= form.radio_button :status, 'private', id: "status2"%>
                        </label>

                        <label class="btn btn-outline-primary" for="status3"> Archived
                            <%= form.radio_button :status, 'archived', id: "status3"%>
                        </label>  
                    </div>
                </div>
            </div>

            <div class='col-6 d-grid d-sm-flex justify-content-sm-center py-3'>
                <%= form.submit :Submit, class: "btn btn-outline-secondary btn-lg" %>
            </div>
        </div>
    </div>
<%end%>

app/views/articles/_profile.html.erb
<div class="container d-line border-bottom">
    <div class="row pt-3">
        <div class="col-6 text-center m-auto d-table">
            <img src="/images/user.svg" style="max-width:40%; min-width:20px">
            <p class='mt-3' style='font-size: 20px'>
                <%= User.find(article[:user_id])[:email]%>
            </p>
        </div>

        <div class="col-6 text-center m-auto d-table">
            <p class='pb-4' style='font-size: 20px'>
                I am a team player. I am outgoing, dedicated, and open-minded. 
                I get across to people and adjust to changes with ease. I believe 
                that a person should work on developing their professional skills 
                and learning new things all the time.
            </p>
            <% if current_user &&  article[:user_id]!=current_user[:id] && !User.find(article[:user_id]).followers.include?(current_user)%>
                <%= link_to 'Follow Me', follow_index_path({article: article}),
                                    method: :create,
                                    type: 'button',
                                    class: "btn btn-primary btn-lg ml-3 mb-3"%>
            <% else %>
                <%= link_to 'Follow Me', follow_index_path({article: article}),
                                    method: :create,
                                    type: 'button',
                                    class: "btn btn-primary btn-lg ml-3 mb-3 disabled"%>
            <% end %>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<%= render "shared/header", article: @article, title: 'Edit Article'%>
<%= render "form", article: @article%>

app/views/articles/index.html.erb
<%= render "shared/header", article: @article, title: 'Articles Blog'%>

<div class="container">
    <!--Our blog has <%= Article.public_count %> articles and counting!-->

    <div class="container">
        <div class="d-flex justify-content-center p-5">
            <button type="button" class="btn btn-primary btn-lg" style="width:100%">
                <%= link_to "Add a New Article", new_article_path, class: "text-white" %>
            </button>
        </div>
    </div>

    <div class="list-group">
        <% @articles.each do |article| %>
            <% unless article.archived? %>
                <div class="row list-group-item d-flex justify-content-between align-items-start">
                    <%# Button %>
                    <div class="col-9 p-5">
                        <%= link_to article.title, article, style: "font-size: 23px"%><br>
                        By: <%= User.find(article[:user_id]).email%>
                    </div>
                    <%# Reading time %>
                    <div class="col-3 m-auto">
                        <p class="text-center" style="font-size:19px">
                            <%= (article.body.split.length/250.0).ceil %> Minutes Reading
                        </p>
                        <%= render "comments_score", article: article%>
                    </div>
                </div>                
            <% end %>
        <%end%>
    </div>
</div>

<footer style="height: 50px"></footer>

app/views/articles/new.html.erb
<%= render "shared/header", article: @article, title: 'New Article'%>
<%= render "form", article: @article%>

app/views/articles/show.html.erb
<%= render "shared/header", article: @article, title: 'Articles Blog'%>

<%# Title and score %>
<header>
    <div class="p-5 pb-md-4 mx-auto text-center">
        <h1 class="display-2 fw-normal"><%= @article.title %></h1>
    </div>
    <div class="container d-flex justify-content-between">
        <div class="py-md-3 text-left" style="font-size:20px">
            By: <%= User.find(@article[:user_id]).email%>
        </div>
        <div class="p-md-2 mb-3 text-right border border-warning rounded" style="font-size:25px; border-width: 3px;">
            <%= @article.score%>
        </div>
    </div>
</header>


<%# Articles %>
<div class="container px-4">
    <% @article.body.split("\n").each do |paragraph|%>
        <p class="text-justify" style="font-size:20px"><%= paragraph%></p>
    <% end %>
</div>


<%# Edit and destroy buttons %>

<div class="container border-bottom">
    <div class="d-grid d-sm-flex justify-content-sm-end">
        <button class="btn btn-secondary btn-lg pr-5 m-3" type="button">
            <%= link_to "Edit", edit_article_path(@article), class: "text-white" %>    
        </button>
        <button class="btn btn-secondary btn-lg pr-5 m-3" type="button">
            <%= link_to "Destroy", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "text-white" %>    
        </button>
    </div>
</div>

<%# What do you think? message %>
<div class="container px-4">
    <div class="p-4 pb-md-4 mx-auto text-center">
        <h2>About the Blogger</h2>
    </div>
</div>

<%# Blogger profile %>
<%= render 'profile', article: @article %>

<%# What do you think? message %>
<div class="container px-4">
    <div class="p-4 pb-md-4 mx-auto text-center">
        <h2 class="display-4 fw-normal">What do you think?</h2>
    </div>
</div>

<%# Add Comments %>
<%= render 'comments/form' %>

<%# What people think? message %>
<div class="container px-4 pt-5">
    <div class="p-4 pb-md-4 mx-auto text-center">
        <h2 class="display-4 fw-normal">What do people think?</h2>
    </div>
</div>

<%# Comments %>
<%= render @article.comments[0...-1] %>

<footer style="height: 50px"></footer>

app/views/comments/_comment.html.erb
<div class="cotnainer mt-4 mx-5 border-top">
    <div class="text-center mt-3 mx-5">
        <p style="font-size:20px">
            <%= comment.commenter %> <strong>says...</strong> <%= comment.body %>
            <strong>and gives a score of...</strong> <%=comment.score%>
        </p>
    </div>
    <div class="d-grid d-sm-flex justify-content-sm-end pr-3 pb-3">
        <%= link_to 'Destroy Comment', 
            [comment.article, comment], 
            method: :delete,data: {confirm: 'Are you sure?'} %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@article, @article.comments.build] do |form| %>

    <div class=container>
        <div class="d-grid d-sm-flex justify-content-sm-center pr-3 pb-3 input-group">
            <span class="input-group-text">I'm</span>
            <%= form.text_field :commenter, class: "form-control"%>
        </div>

        <div class="d-grid d-sm-flex justify-content-sm-center pr-3 pb-3 input-group">
            <span class="input-group-text">And, I think </span>
            <%= form.text_area :body, class: "form-control" %>
        </div>
    </div>

    <div class="container border-bottom">
        <div class="row">
            <%# Status %>
            <div class='col-4 justify-content-sm-center m-auto'>
                <p class="text-center d-flex justify-content-sm-center" style="font-size:20px">
                    Comment status
                </p>
                <div class="container d-flex justify-content-center">
                    <div class="btn-group d-table justify-content-sm-center" role="group">
                        <label class="btn btn-outline-primary" for="status1"> Public
                            <%= form.radio_button :status, 'public', id: "status1",class: "btn-check", autocomplete: "off",checked: true%>
                        </label>

                        <label class="btn btn-outline-primary" for="status2"> Private
                            <%= form.radio_button :status, 'private', id: "status2"%>
                        </label>

                        <label class="btn btn-outline-primary" for="status3"> Archived
                            <%= form.radio_button :status, 'archived', id: "status3"%>
                        </label>  
                    </div>
                </div>
            </div>
            <%# Score %>
            <div class='col-4 d-grid justify-content-sm-center m-auto'>
                <p class="text-center d-flex justify-content-sm-center" style="font-size:20px">
                    How much do you like the article?
                </p>
                <div class="container d-flex justify-content-center">
                    <div class="btn-group d-table" role="group">
                        <% (1..5).to_a.each do |index| %>
                            <label class="btn btn-outline-primary" for="score"+<%=index.to_s%>>
                                <%=index%>
                                <%= form.radio_button :score, index, 
                                                        id:"score"+index.to_s,
                                                        class: "btn-check",
                                                        checked: true%>
                            </label>
                        <% end %>
                    </div>
                </div>
                
            </div>
            <%# Send botton %>
            <div class='col-4 d-grid d-sm-flex justify-content-sm-center m-auto'>
                <%= form.submit :Submit, class: "btn btn-outline-secondary btn-lg" %>
            </div>

        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/modal", resource: notice%>
    <%= render "shared/modal", resource: alert%>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header class="py-3 bg-dark text-white">
    <div class="d-flex pl-5">
        <% if title == 'New Article' || title == 'Edit Article'%>
            <a class="text-white text-decoration-none mr-auto">
        <% else %>
            <a class="text-white text-decoration-none mr-auto" href="/">
        <% end %>
                <span style="font-size:40px"><%=title%></span>
            </a>
        

        <div class="justify-content-end mr-5 mt-2">
            <% if user_signed_in? %>
                <% case title %>
                <% when 'New Article' %>
                    <%= link_to 'Cancel', root_path, type: 'button',class: 'btn btn-primary'%>
                <% when 'Edit Article' %>
                    <%= link_to 'Cancel', article, type: 'button',class: 'btn btn-primary'%>
                <% else %>
                    <div class="d-flex">
                        <p class='my-auto'>
                            <%= link_to current_user[:email], User.find(current_user[:id]), class: 'text-white'%>
                        </p>
                        <%= link_to 'Sign out', destroy_user_session_path, 
                            method: :delete, 
                            type: 'button',
                            class: 'btn btn-primary ml-4'%>
                    </div>
                <% end %>
            <% else %>
                <% if title== 'Sign Up' || title == 'Sign In' %>
                    <%= link_to 'Cancel', root_path, type: 'button',class: 'btn btn-primary'%>
                <% else %>
                    <%= link_to 'Sign up', new_user_registration_path, type: 'button',class: 'btn btn-primary'%>
                    <%= link_to 'Sign in', new_user_session_path, type: 'button',class: 'btn btn-primary'%>
                <% end %>
            <% end %>
        </div>
    </div>
</header>

app/views/shared/_modal.html.erb
<% if resource%>
  <div class="alert alert-success" role="alert">
    <%= resource %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= render "shared/header", article: @article, title: 'Articles Blog'%>

<div class='container mt-5'>
    <div class='row'>
        <div class='col-4 text-center'>
            <img src="/images/user.svg" style="max-width:60%; min-width:20px">
            <h5 class='mt-3'><strong>User:</strong> <%= @user.email %></h5>
            <h5>
                <strong>Followers:</strong> <%= @user.followers.length %> /
                <strong>Followees:</strong> <%= @user.followees.length %>
            </h5>
            <p class='pt-3 border-top' style='font-size: 20px'>
                I am a team player. I am outgoing, dedicated, and open-minded. 
                I get across to people and adjust to changes with ease. I believe 
                that a person should work on developing their professional skills 
                and learning new things all the time.
            </p>
        </div>
        <div class='col ml-4'>
            <h2>Followed by:</h2>
            <% @user.followers.each do |follower|%>
                <div class="row list-group-item d-flex justify-content-between align-items-start">
                    <p style='font-size:20px'>
                        user: <%=follower[:email]%>
                    </p>
                </div>
            <% end %>

            <h2 class='mt-4'>Following:</h2>
            <% @user.followees.each do |followee|%>
                <div class="row list-group-item d-flex justify-content-between align-items-start">
                    <p style='font-size:20px'>
                        user: <%=followee[:email]%>
                    </p>
                    <%= link_to 'Unfollow Me', follow_path(follower: @user,followee: followee),
                                    method: :delete,
                                    type: 'button',
                                    class: "btn btn-primary btn-md ml-3 mb-3"%>
                </div>
            <% end %>
        </div>
    </div>
</div>